apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: "${project_name}-rpt-db-svc"
    namespace: ${project_name}
  spec:
    ports:
      - name: postgresql
        port: 5432
        protocol: TCP
        targetPort: 5432
    selector:
      app: ${project_name}
      deploymentconfig: "${project_name}-dc"
      name: postgres
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- name: project_name
  required: true