
apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${project_name}-rpt-db-cm
  data:
    PGHOST: "${project_name}-rpt-db-svc"
parameters:
- name: project_name
  required: true